'use strict';
const E=window.TucannEngine;
const $=id=>document.getElementById(id);
const ui={fileInput:$('fileInput'),dropZone:$('dropZone'),fileList:$('fileList'),fileCount:$('fileCount'),presetSelect:$('presetSelect'),canvasWidth:$('canvasWidth'),canvasHeight:$('canvasHeight'),backgroundMode:$('backgroundMode'),customColorWrap:$('customColorWrap'),customBgColor:$('customBgColor'),tolerance:$('tolerance'),toleranceValue:$('toleranceValue'),contentScale:$('contentScale'),contentScaleValue:$('contentScaleValue'),normalizeMode:$('normalizeMode'),vectorColors:$('vectorColors'),edgeCleanup:$('edgeCleanup'),smoothRaster:$('smoothRaster'),keepInside:$('keepInside'),processBtn:$('processBtn'),downloadZipBtn:$('downloadZipBtn'),status:$('status'),progressWrap:$('progressWrap'),progressBar:$('progressBar'),beforeTab:$('beforeTab'),afterTab:$('afterTab'),beforePreview:$('beforePreview'),afterPreview:$('afterPreview'),previewEmpty:$('previewEmpty'),previewTitle:$('previewTitle'),metrics:$('metrics'),installBtn:$('installBtn')};
const state={items:[],referenceId:null,selectedId:null,showAfter:false,processing:false};
const key='tucann-normalizer-v2';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const safe=n=>(n||'logo').replace(/\.[^.]+$/,'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'_').replace(/^_+|_+$/g,'')||'logo';
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function settings(){return{width:Math.max(256,Math.min(4096,+ui.canvasWidth.value||1600)),height:Math.max(256,Math.min(4096,+ui.canvasHeight.value||900)),backgroundMode:ui.backgroundMode.value,customBgColor:ui.customBgColor.value,tolerance:+ui.tolerance.value||0,contentScale:(+ui.contentScale.value||78)/100,normalizeMode:ui.normalizeMode.value,vectorColors:+ui.vectorColors.value||4,edgeCleanup:ui.edgeCleanup.checked,smoothRaster:ui.smoothRaster.checked,keepInside:ui.keepInside.checked,maxInputDimension:2200};}
function save(){try{localStorage.setItem(key,JSON.stringify({...settings(),preset:ui.presetSelect.value}));}catch(_){}}
function load(){try{const s=JSON.parse(localStorage.getItem(key));if(!s)return;ui.presetSelect.value=s.preset||'1600x900';ui.canvasWidth.value=s.width||1600;ui.canvasHeight.value=s.height||900;ui.backgroundMode.value=s.backgroundMode||'auto';ui.customBgColor.value=s.customBgColor||'#fff';ui.tolerance.value=s.tolerance??24;ui.contentScale.value=Math.round((s.contentScale||.78)*100);ui.normalizeMode.value=s.normalizeMode||'symbol';ui.vectorColors.value=s.vectorColors||4;ui.edgeCleanup.checked=s.edgeCleanup!==false;ui.smoothRaster.checked=s.smoothRaster!==false;ui.keepInside.checked=s.keepInside!==false;}catch(_){}}
function labels(){ui.toleranceValue.textContent=ui.tolerance.value;ui.contentScaleValue.textContent=ui.contentScale.value+'%';ui.customColorWrap.classList.toggle('hidden',ui.backgroundMode.value!=='custom');}
function status(t,bad=false){ui.status.textContent=t;ui.status.style.color=bad?'#ef4444':'';}
function progress(n,total){ui.progressWrap.classList.remove('hidden');ui.progressBar.style.width=Math.round(n/Math.max(1,total)*100)+'%';}
function invalidate(){state.items.forEach(x=>{x.canvas=null;x.svg=null;x.error=null;x.metrics=null;});ui.downloadZipBtn.disabled=true;buttons();}
function buttons(){ui.processBtn.disabled=!state.items.length||state.processing;ui.downloadZipBtn.disabled=state.processing||!state.items.length||!state.items.every(x=>x.canvas&&!x.error);}
async function addFiles(list){const files=[...list].filter(f=>f.type.startsWith('image/')||/\.(png|jpe?g|webp|heic|heif)$/i.test(f.name));if(!files.length)return;status('Wczytywanie plików…');for(const f of files){try{const image=await E.decode(f),item={id:uid(),file:f,image,name:f.name,url:URL.createObjectURL(f),canvas:null,svg:null,error:null};state.items.push(item);state.referenceId||=item.id;state.selectedId||=item.id;}catch(e){status('Pominięto '+f.name+': '+e.message,true);}}invalidate();renderList();preview();status('Dodano '+state.items.length+' plików. Pierwszy jest wzorcem.');}
function renderList(){ui.fileCount.textContent=state.items.length+' '+(state.items.length===1?'plik':'plików');ui.fileList.innerHTML='';ui.fileList.classList.toggle('empty-state',!state.items.length);if(!state.items.length){ui.fileList.innerHTML='<p>Dodane pliki pojawią się tutaj.</p>';buttons();return;}for(const item of state.items){const c=document.createElement('div');c.className='file-card'+(item.id===state.selectedId?' selected':'');c.innerHTML=`<img class="file-thumb" src="${item.url}" alt=""><div class="file-info"><span class="file-name">${esc(item.name)}</span><div class="file-meta">${item.id===state.referenceId?'<span class="reference-tag">WZORZEC</span>':''}<span>${item.error?'Błąd':item.canvas?'Gotowe':'Oczekuje'}</span></div></div><div class="file-actions"><button class="icon-btn ref" type="button">★</button><button class="icon-btn del" type="button">×</button>${item.canvas?'<button class="icon-btn png" type="button">PNG</button><button class="icon-btn svg" type="button">SVG</button>':''}</div>`;c.onclick=e=>{if(!e.target.closest('button')){state.selectedId=item.id;renderList();preview();}};c.querySelector('.ref').onclick=e=>{e.stopPropagation();state.referenceId=item.id;invalidate();renderList();preview();status('Zmieniono wzorzec.');};c.querySelector('.del').onclick=e=>{e.stopPropagation();URL.revokeObjectURL(item.url);state.items=state.items.filter(x=>x.id!==item.id);if(state.referenceId===item.id)state.referenceId=state.items[0]?.id||null;if(state.selectedId===item.id)state.selectedId=state.items[0]?.id||null;invalidate();renderList();preview();};c.querySelector('.png')?.addEventListener('click',async e=>{e.stopPropagation();E.download(await E.blob(item.canvas),safe(item.name)+'_normalized.png');});c.querySelector('.svg')?.addEventListener('click',async e=>{e.stopPropagation();item.svg||=E.vectorize(item.canvas,+ui.vectorColors.value||4);E.download(item.svg,safe(item.name)+'_vector.svg','image/svg+xml');});ui.fileList.appendChild(c);}buttons();}
function preview(){const item=state.items.find(x=>x.id===state.selectedId);ui.previewEmpty.classList.toggle('hidden',!!item);ui.beforePreview.classList.toggle('hidden',!item||state.showAfter);ui.afterPreview.classList.toggle('hidden',!item||!state.showAfter||!item.canvas);ui.previewTitle.textContent=item?.name||'Brak wybranego pliku';if(item){ui.beforePreview.src=item.url;if(item.canvas){ui.afterPreview.width=item.canvas.width;ui.afterPreview.height=item.canvas.height;ui.afterPreview.getContext('2d').drawImage(item.canvas,0,0);}}ui.beforeTab.classList.toggle('active',!state.showAfter);ui.afterTab.classList.toggle('active',state.showAfter);const vals=item?.metrics?[item.id===state.referenceId?'Tak':'Nie',Math.round(item.metrics.symbol.w)+'×'+Math.round(item.metrics.symbol.h),item.metrics.scale.toFixed(3),'Gotowe']:['—','—','—',item?.error?'Błąd':'Oczekuje'];[...ui.metrics.querySelectorAll('strong')].forEach((x,i)=>x.textContent=vals[i]);}
async function processAll(){if(state.processing||!state.items.length)return;state.processing=true;buttons();ui.processBtn.textContent='Przetwarzanie…';const s=settings();save();progress(0,state.items.length);try{const ref=state.items.find(x=>x.id===state.referenceId)||state.items[0];state.referenceId=ref.id;status('Analiza wzorca: '+ref.name);const rp=await E.prepare(ref.image,s),rr=E.render(rp,null,s,true),target={overall:rr.overall,symbol:rr.symbol};ref.canvas=rr.canvas;ref.metrics=rr;let done=1;progress(done,state.items.length);for(const item of state.items){if(item===ref)continue;try{status(`Poprawianie ${done+1}/${state.items.length}: ${item.name}`);const p=await E.prepare(item.image,s),r=E.render(p,target,s,false);item.canvas=r.canvas;item.metrics=r;item.error=null;}catch(e){item.error=e.message;}done++;progress(done,state.items.length);await E.nextFrame();}state.showAfter=true;renderList();preview();const errors=state.items.filter(x=>x.error).length;status(errors?'Gotowe, ale '+errors+' plików ma błąd.':'Gotowe. Możesz pobrać PNG, SVG lub ZIP.',!!errors);}catch(e){status('Błąd: '+e.message,true);}finally{state.processing=false;ui.processBtn.textContent='Popraw wszystkie';ui.progressWrap.classList.add('hidden');buttons();}}
async function zipAll(){if(ui.downloadZipBtn.disabled)return;state.processing=true;buttons();try{const zip=new JSZip(),p=zip.folder('PNG'),v=zip.folder('SVG');let n=0;for(const item of state.items){status('Pakowanie: '+item.name);p.file(safe(item.name)+'_normalized.png',await E.blob(item.canvas));item.svg||=E.vectorize(item.canvas,+ui.vectorColors.value||4);v.file(safe(item.name)+'_vector.svg',item.svg);progress(++n,state.items.length);await E.nextFrame();}zip.file('README.txt','Pliki przygotowane przez TUCANN Logo Normalizer. SVG jest wynikiem automatycznej wektoryzacji i przed drukiem wielkoformatowym warto go skontrolować.');const b=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});E.download(b,'TUCANN_logo_'+new Date().toISOString().slice(0,10)+'.zip');status('Paczka ZIP została pobrana.');}catch(e){status('Błąd ZIP: '+e.message,true);}finally{state.processing=false;ui.progressWrap.classList.add('hidden');buttons();}}
ui.fileInput.onchange=e=>addFiles(e.target.files);['dragenter','dragover'].forEach(n=>ui.dropZone.addEventListener(n,e=>{e.preventDefault();ui.dropZone.classList.add('dragover');}));['dragleave','drop'].forEach(n=>ui.dropZone.addEventListener(n,e=>{e.preventDefault();ui.dropZone.classList.remove('dragover');}));ui.dropZone.ondrop=e=>addFiles(e.dataTransfer.files);
ui.presetSelect.onchange=()=>{if(ui.presetSelect.value!=='custom'){[ui.canvasWidth.value,ui.canvasHeight.value]=ui.presetSelect.value.split('x');}invalidate();save();};[ui.canvasWidth,ui.canvasHeight].forEach(x=>x.onchange=()=>{ui.presetSelect.value='custom';invalidate();save();});[ui.backgroundMode,ui.customBgColor,ui.tolerance,ui.contentScale,ui.normalizeMode,ui.vectorColors,ui.edgeCleanup,ui.smoothRaster,ui.keepInside].forEach(x=>{x.oninput=x.onchange=()=>{labels();save();if(x!==ui.vectorColors)invalidate();};});ui.processBtn.onclick=processAll;ui.downloadZipBtn.onclick=zipAll;ui.beforeTab.onclick=()=>{state.showAfter=false;preview();};ui.afterTab.onclick=()=>{state.showAfter=true;preview();};
load();labels();renderList();preview();
